import type { Diagnosis, ContainerDiagnosis, WarningEvent } from './types';

/**
 * Produce a `kubectl describe`-style plain text representation of a Diagnosis
 * suitable for copying to the clipboard and pasting into Slack/tickets.
 *
 * Stable, deterministic output. The only non-deterministic field is the
 * "Diagnosed" timestamp in the header, which is expected to vary.
 */
export function toDescribeText(
  diagnosis: Diagnosis,
  resource: { metadata: { name: string; namespace?: string } }
): string {
  const lines: string[] = [];

  const fqn = `${diagnosis.namespace ?? resource.metadata.namespace ?? 'default'}/${diagnosis.name}`;
  lines.push(`Kubilitics Diagnose — ${fqn}`);
  lines.push(`Kind:       ${diagnosis.kind}`);
  lines.push(`Severity:   ${diagnosis.severity.toUpperCase()}`);
  lines.push(`Headline:   ${diagnosis.headline}`);
  lines.push(`Diagnosed:  ${new Date(diagnosis.computedAt).toISOString()}`);
  lines.push('');

  // Status block
  lines.push('Status');
  if (diagnosis.conditions.length > 0) {
    lines.push('  Conditions:');
    for (const c of diagnosis.conditions) {
      const tail = c.reason ? ` (${c.reason})` : '';
      lines.push(`    ${c.type.padEnd(20)} ${c.status}${tail}`);
    }
  } else {
    lines.push('  Conditions: (none)');
  }
  lines.push('');

  // Containers block
  if (diagnosis.containers.length > 0) {
    lines.push('Containers');
    for (const c of diagnosis.containers) {
      formatContainer(lines, c);
    }
    lines.push('');
  }

  // Reasons / likely causes
  if (diagnosis.reasons.length > 0 && diagnosis.severity !== 'healthy') {
    lines.push('Likely Causes');
    diagnosis.reasons.forEach((r, i) => {
      lines.push(`  ${i + 1}. ${r.title}`);
      lines.push(`     ${r.explanation}`);
      for (const s of r.suggestions) {
        const hint = s.kubectlHint
          ? s.kubectlHint
              .replace('{namespace}', diagnosis.namespace ?? 'default')
              .replace('{pod}', diagnosis.name)
          : '';
        lines.push(`     - ${s.text}${hint ? `\n       ${hint}` : ''}`);
      }
    });
    lines.push('');
  }

  // Recent warnings
  if (diagnosis.recentWarnings.length > 0) {
    lines.push(`Recent Warnings (last ${diagnosis.recentWarnings.length})`);
    for (const w of diagnosis.recentWarnings) {
      formatWarning(lines, w);
    }
    lines.push('');
  }

  lines.push('--');
  lines.push('Generated by Kubilitics Diagnose');

  return lines.join('\n');
}

function formatContainer(lines: string[], c: ContainerDiagnosis): void {
  const tag = c.isInit ? 'init ' : '';
  lines.push(`  ${tag}${c.name}`);
  const stateLabel = c.reason ? `${capitalize(c.state)} (${c.reason})` : capitalize(c.state);
  lines.push(`    State:         ${stateLabel}`);
  lines.push(`    Ready:         ${c.ready ? 'True' : 'False'}`);
  lines.push(`    Restart Count: ${c.restartCount}`);
  if (c.lastTerminated) {
    lines.push('    Last State:    Terminated');
    if (c.lastTerminated.reason) lines.push(`      Reason:      ${c.lastTerminated.reason}`);
    lines.push(`      Exit Code:   ${c.lastTerminated.exitCode}`);
    if (c.lastTerminated.finishedAt) lines.push(`      Finished:    ${c.lastTerminated.finishedAt}`);
    if (c.lastTerminated.message) {
      lines.push('      Message:');
      wrapText(c.lastTerminated.message, 8, 80).forEach(l => lines.push(l));
    }
  }
}

function formatWarning(lines: string[], w: WarningEvent): void {
  const ageMs = Date.now() - w.lastSeen;
  const age = humanAge(ageMs);
  const head = `  ${age}  Warning  ${w.reason.padEnd(20)} (x${w.count})`;
  lines.push(head);
  wrapText(w.message, 4, 80).forEach(l => lines.push(l));
}

function wrapText(text: string, indent: number, width: number): string[] {
  const padding = ' '.repeat(indent);
  const out: string[] = [];
  const rawLines = text.split('\n');
  for (const raw of rawLines) {
    let line = raw;
    while (line.length > width) {
      const brk = line.lastIndexOf(' ', width);
      const cut = brk > 0 ? brk : width;
      out.push(padding + line.slice(0, cut));
      line = line.slice(cut).trimStart();
    }
    if (line.length > 0) out.push(padding + line);
  }
  return out;
}

function humanAge(ms: number): string {
  const s = Math.max(0, Math.floor(ms / 1000));
  if (s < 60) return `${s}s ago`;
  const m = Math.floor(s / 60);
  if (m < 60) return `${m}m ago`;
  const h = Math.floor(m / 60);
  if (h < 24) return `${h}h ago`;
  return `${Math.floor(h / 24)}d ago`;
}

function capitalize(s: string): string {
  return s.charAt(0).toUpperCase() + s.slice(1);
}
